sim_cmd.c: Delete unused update of a value
Issue was detected by Coverity.

Error: CLANG_WARNING: [#def3]
ibsim-0.7/ibsim/sim_cmd.c:540:3: warning: Value stored to 'n' is never read
//                n += sprintf(comment+n, "\t# err_attr %d", port->errattr);
//                ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibsim-0.7/ibsim/sim_cmd.c:540:3: note: Value stored to 'n' is never read
//                n += sprintf(comment+n, "\t# err_attr %d", port->errattr);
//                ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//  538|   		n += sprintf(comment, "\t# err_rate %d", port->errrate);
//  539|   	if (port->errattr)
//  540|-> 		n += sprintf(comment+n, "\t# err_attr %d", port->errattr);
//  541|   }
//  542|

Signed-off-by: Honggang Li <honli@redhat.com>
Signed-off-by: Hal Rosenstock <hal@mellanox.com>