ibsim: Fixed custom release in SPEC file
Removed a space which make rpmbuild fail when _dist and CUSTOM_RELEASE are set:
error: line 15: Tag takes single token only: Release: ofed1.4.1 .fc11

This is due to
Release: %rel%{?dist}
and %rel having a trailing whitespace.

Signed-off-by: Nicolas Morey-Chaisemartin <nicolas.morey-chaisemartin@ext.bull.net>
Signed-off-by: Sasha Khapyorsky <sashak@voltaire.com>